version: "3.9"
services:
  web:
    build: .
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:password@db:5432/autumn_quiz_production
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: autumn_quiz_production
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
